languageCode:           "en"
title:                  "Flowbite"
baseURL:                "https://flowbite.com/docs/"
enableInlineShortcodes: true

params:
  homepage: "https://flowbite.com"
  current_version: 1.8.1
  authors: Themesberg
  social_image_path: /docs/images/og-image.png

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
    style:              colorful
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"
